### ISSUE TITLE
Intensity measurement in additional channels

### ISSUE THREAD

**Issue by Cryaaa** [haesleinhuepf/napari-skimage-regionprops#23]
@jo-mueller suggested this for the napari-cluster-plotter but I think it could be more fitting here:
It would be a nice-to-have to be able to measure intensity values in more than just one image (different channels with different markers). The actual coding should not be very difficult but the gui implementation of it might be slightly more challenging.

**Comment by haesleinhuepf** [comment]
Great idea! I'm just curious, is it possible to define a `List[ImageData]` as parameter so that magicgui builds a multi-selection widget? If not, we might have to make it. And we should do it as PR to [magicgui](https://github.com/napari/magicgui). We're using something similar in [napari-apoc](https://github.com/haesleinhuepf/napari-accelerated-pixel-and-object-classification/blob/main/napari_accelerated_pixel_and_object_classification/_dock_widget.py#L41) and I think it would be of general interest to have it.

**Comment by jo-mueller** [comment]
That would be super helpful to do in magicgui. According to the [documentation](https://napari.org/api/napari.types.html#module-napari.types) magicgui supports any of the napari.layers types, but we would need a list of these types.

I think the actual challenge for this is that the number of layers one would like to feed to a plugin (like in the above usecase) is not clear at the time the magicgui instance is created. 

A solution I could imagine would be:

- Putting the layer selection widget into a vertical layout
- Selecting an image layer in the dropdown would have to trigger the creation of another dropdown in the same layout
  - repeat this for the newly created dropdown until all images are added
- The dropdowns would need an option to make them disappear to prevent spawning an unreasonable amount of dropdowns^^

As for magicgui, this could be implemented by adding an option to the magic_factory decorator that implements the incremental addition of multiple dropdowns. But I think the trickiest part is modifying magicgui widgets after they have already been created.

**Comment by haesleinhuepf** [comment]
Done in #50
